"""Deterministic, structure-only category intelligence for ContentEngine."""

from .schema import (
    DEFAULT_STAGE_ORDER,
    STRUCTURAL_FEATURES,
    CategoryResearchAssessment,
    CategoryResearchCoverage,
    ContentStage,
    ProactiveNextAction,
    ResearchAction,
    ResearchReadiness,
    StageArtifactVersion,
    StageCorrectionCode,
    StageRevisionGraph,
    StageState,
    StructuralFeature,
    StructuralSignal,
    TrendCorroboration,
    TrendDirection,
    TrendFreshness,
    TrendHypothesis,
)
from .service import (
    CategoryIntelligenceError,
    CategoryIntelligenceService,
    assess_category_research,
    correct_stage,
    new_stage_revision_graph,
    record_stage_output,
)
from .trends import (
    CategoryTrendError,
    ObservationWindows,
    analyze_category_trends,
    build_observation_windows,
    freshness_for,
    structural_signals,
)

__all__ = [
    "DEFAULT_STAGE_ORDER",
    "STRUCTURAL_FEATURES",
    "CategoryIntelligenceError",
    "CategoryIntelligenceService",
    "CategoryResearchAssessment",
    "CategoryResearchCoverage",
    "CategoryTrendError",
    "ContentStage",
    "ObservationWindows",
    "ProactiveNextAction",
    "ResearchAction",
    "ResearchReadiness",
    "StageArtifactVersion",
    "StageCorrectionCode",
    "StageRevisionGraph",
    "StageState",
    "StructuralFeature",
    "StructuralSignal",
    "TrendCorroboration",
    "TrendDirection",
    "TrendFreshness",
    "TrendHypothesis",
    "analyze_category_trends",
    "assess_category_research",
    "build_observation_windows",
    "correct_stage",
    "freshness_for",
    "new_stage_revision_graph",
    "record_stage_output",
    "structural_signals",
]
